theme: jekyll-theme-architect
title: "BI Cearence"
breadcrumbs: true
search: true
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
